const state={items:[],period:null};
const $=s=>document.querySelector(s); const format=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(v)+' ₸';
function parse(value){const [time,date]=value.split(' ');const [h,m]=time.split(':').map(Number);const [d,mo,y]=date.split('.').map(Number);return new Date(y,mo-1,d,h,m)}
function defaultTime(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${p(d.getHours())}:${p(d.getMinutes())} ${p(d.getDate())}.${p(d.getMonth()+1)}.${d.getFullYear()}`}
function filtered(){const q=$('#search').value.trim().toLowerCase(),from=$('#date-from').value,to=$('#date-to').value;return state.items.filter(x=>{const d=parse(x.spentAt);return (!q||x.comment.toLowerCase().includes(q))&&(!from||d>=new Date(from+'T00:00'))&&(!to||d<=new Date(to+'T23:59:59'))})}
function render(){const items=filtered(), rows=$('#rows'); rows.innerHTML=items.map(x=>`<div class="row"><span>${escapeHtml(x.comment)}</span><span class="date">${x.spentAt}</span><span class="amount">${format(x.amount)}</span><button class="delete" title="Удалить" aria-label="Удалить ${escapeHtml(x.comment)}" data-id="${x.id}">×</button></div>`).join('');$('#empty').hidden=items.length>0;$('#total').textContent=format(items.reduce((s,x)=>s+x.amount,0));$('#count').textContent=`${items.length} ${plural(items.length)}`;document.querySelectorAll('.delete').forEach(b=>b.onclick=async()=>{if(confirm('Удалить эту трату?')){await fetch('/api/expenses/'+b.dataset.id,{method:'DELETE'});await load()}})}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}function plural(n){return n%10===1&&n%100!==11?'запись':n%10>=2&&n%10<=4&&!(n%100>=12&&n%100<=14)?'записи':'записей'}
async function load(){state.items=await (await fetch('/api/expenses')).json();render()}
function setPeriod(kind){state.period=kind; const now=new Date(),p=n=>String(n).padStart(2,'0'),asInput=d=>`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`;let start;if(kind==='month-start')start=new Date(now.getFullYear(),now.getMonth(),1);if(kind==='week')start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-6);if(kind==='month')start=new Date(now.getFullYear(),now.getMonth()-1,now.getDate());$('#date-from').value=asInput(start);$('#date-to').value=asInput(now);document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('active',b.dataset.period===kind));render()}
$('#open-form').onclick=()=>{$('#spent-at').value=defaultTime();$('#form-error').textContent='';$('#expense-dialog').showModal()};$('#close-form').onclick=()=>$('#expense-dialog').close();$('#search').oninput=render;$('#date-from').onchange=$('#date-to').onchange=()=>{state.period=null;document.querySelectorAll('[data-period]').forEach(b=>b.classList.remove('active'));render()};document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>setPeriod(b.dataset.period));$('#reset').onclick=()=>{$('#search').value=$('#date-from').value=$('#date-to').value='';state.period=null;document.querySelectorAll('[data-period]').forEach(b=>b.classList.remove('active'));render()};
$('#expense-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data={amount:Number(f.get('amount')),comment:f.get('comment'),spentAt:f.get('spentAt')};const res=await fetch('/api/expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!res.ok){$('#form-error').textContent=await res.text();return}$('#expense-dialog').close();e.target.reset();await load()};load();
